services:
  yogiitsu-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yogiitsu-dev
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - FIREBASE_SERVICE_ACCOUNT_PATH=/run/secrets/firebase-service-account.json
    env_file:
      - ./.env
    volumes:
      - /var/log/yogiitsu/dev:/var/log/yogiitsu/dev
      - /home/ubuntu/YOGIITSU/firebase-service-account.json:/run/secrets/firebase-service-account.json:ro
    restart: always

  yogiitsu-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yogiitsu-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - FIREBASE_SERVICE_ACCOUNT_PATH=/run/secrets/firebase-service-account.json
    env_file:
      - ./.env
    volumes:
      - /var/log/yogiitsu/prod:/var/log/yogiitsu/prod
      - /home/ubuntu/YOGIITSU/firebase-service-account.json:/run/secrets/firebase-service-account.json:ro
    restart: always