services:
  yogiitsu-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yogiitsu-dev
    ports:
      - "8081:8080"
    env_file:
      - ./.env
    volumes:
      - /var/log/yogiitsu/dev:/app/logs
    restart: always

  yogiitsu-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yogiitsu-prod
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - /var/log/yogiitsu/prod:/app/logs
    restart: always